Repository NibiruChain/ts-sdk, pull requests merged in 2022-10, with the labels that each got.

#31 feat: 'vpool' and 'pricefeed' module extensions
  packages/nibijs/package.json
  packages/nibijs/src/query/pricefeed.ts
  packages/nibijs/src/query/query.test.ts
  packages/nibijs/src/query/query.ts
Labels: type: test, type: feat

#32 refactor: fix linter and make updates
  .eslintrc.js
  packages/nibijs/.eslintrc.js
  packages/nibijs/package.json
  packages/nibijs/src/chain.test.ts
  packages/nibijs/src/chain/chain.ts
  packages/nibijs/src/chain/constants.ts
  packages/nibijs/src/chain/parse.test.ts
  packages/nibijs/src/chain/parse.ts
  packages/nibijs/src/chain/types.ts
  packages/nibijs/src/msg/index.ts
  packages/nibijs/src/query/pricefeed.ts
  packages/nibijs/src/query/query.test.ts
  packages/nibijs/src/query/query.ts
  packages/nibijs/src/query/vpool.ts
  packages/nibijs/src/sdk.ts
  packages/nibijs/src/tx.test.ts
  packages/nibijs/src/tx/signer.test.ts
  packages/nibijs/src/tx/signer.ts
  packages/nibijs/src/tx/tx.ts
  tsconfig.json
  yarn.lock
Labels: type: refactor, type: chore

#42 feat: event and number parsing improvements
  .gitignore
  examples/01_new-wallet-and-faucet.ts
  examples/02_queries.ts
  examples/03_messages.ts
  examples/package.json
  examples/yarn.lock
  packages/nibijs/package.json
  packages/nibijs/src/chain.test.ts
  packages/nibijs/src/chain/parse.test.ts
  packages/nibijs/src/chain/parse.ts
  packages/nibijs/src/chain/types.ts
  packages/nibijs/src/msg/perp.ts
  packages/nibijs/src/query/perp.ts
  packages/nibijs/src/query/query.test.ts
  packages/nibijs/src/query/vpool.ts
  packages/nibijs/src/tx.test.ts
Labels: type: refactor, type: test, type: feat

#44 staking query
  packages/nibijs/src/msg/index.ts
  packages/nibijs/src/msg/staking.ts
  packages/nibijs/src/query/staking.ts
Labels: type: feat

#47 feat: parse response from faucet and add logic to wait for blocks when a tx simulation fails
  .eslintrc.js
  packages/nibijs/package.json
  packages/nibijs/src/chain.test.ts
  packages/nibijs/src/chain/chain.ts
  packages/nibijs/src/tx/tx.ts
Labels: type: feat

#46 feat: add query positions
  examples/01_new-wallet-and-faucet.ts
  examples/02_queries.ts
  examples/03_messages.ts
  jest.config.js
  packages/nibijs/package.json
  packages/nibijs/src/chain.test.ts
  packages/nibijs/src/chain/chain.ts
  packages/nibijs/src/chain/types.ts
  packages/nibijs/src/msg/staking.ts
  packages/nibijs/src/query/perp.ts
  packages/nibijs/src/query/staking.ts
  packages/nibijs/src/tx.test.ts
  packages/nibijs/src/tx/tx.ts
  yarn.lock
Labels: type: refactor, type: feat
