Repository NibiruChain/ts-sdk, pull requests merged in 2023-06, with the labels that each got.

#159 docs(docs): Stableswap
  packages/nibijs/src/stableswap/stableswap.ts
Labels: type: docs

#160 feat(leaderboard): perp leaderboard
  packages/indexer-nibi/CHANGELOG.md
  packages/indexer-nibi/package.json
  packages/indexer-nibi/src/heart-monitor.test.ts
  packages/indexer-nibi/src/heart-monitor.ts
  packages/indexer-nibi/src/query/perpLeaderboard.ts
Labels: type: feat

#161 fix(precision): add BigNumber
  packages/nibijs/package.json
  packages/nibijs/src/stableswap/stableswap.ts
  packages/nibijs/src/test/mocks/stabletests.csv
  packages/nibijs/src/test/stableswap.test.ts
  yarn.lock
Labels: type: bug/fix

#162 Fix/publish
  packages/indexer-nibi/CHANGELOG.md
  packages/indexer-nibi/package.json
  packages/nibijs/README.md
Labels: type: feat

#163 fix(fix): build/publish
  package.json
  packages/indexer-nibi/CHANGELOG.md
  packages/indexer-nibi/package.json
  packages/nibijs/CHANGELOG.md
  packages/nibijs/docs/classes/CustomChain.md
  packages/nibijs/docs/classes/MsgFactory.md
  packages/nibijs/docs/classes/NibiruQueryClient.md
  packages/nibijs/docs/classes/NibiruSigningClient.md
  packages/nibijs/docs/classes/PerpMsgFactory.md
  packages/nibijs/docs/classes/SpotMsgFactory.md
  packages/nibijs/docs/enums/BECH32_PREFIX.md
  packages/nibijs/docs/enums/Signer.md
  packages/nibijs/docs/interfaces/Attribute.md
  packages/nibijs/docs/interfaces/Chain.md
  packages/nibijs/docs/interfaces/ChainIdParts.md
  packages/nibijs/docs/interfaces/CoinMap.md
  packages/nibijs/docs/interfaces/Event.md
  packages/nibijs/docs/interfaces/MsgAddMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgClosePositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgCreatePoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgDonateToEcosystemFundEncodeObject.md
  packages/nibijs/docs/interfaces/MsgExitPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgJoinPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgMultiLiquidateEncodeObject.md
  packages/nibijs/docs/interfaces/MsgOpenPositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgRemoveMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgSwapAssetsEncodeObject.md
  packages/nibijs/docs/interfaces/MsgTypeUrls.md
  packages/nibijs/docs/interfaces/TxLog.md
  packages/nibijs/docs/interfaces/TxMessage.md
  packages/nibijs/docs/intro.md
  packages/nibijs/docs/modules.md
  packages/nibijs/package.json
  packages/protojs/package.json
Labels: type: bug/fix, type: feat

#166 feat(upgrade): keplr
  package.json
  packages/indexer-nibi/CHANGELOG.md
  packages/indexer-nibi/package.json
  packages/nibijs/CHANGELOG.md
  packages/nibijs/docs/classes/CustomChain.md
  packages/nibijs/docs/classes/MsgFactory.md
  packages/nibijs/docs/classes/NibiruQueryClient.md
  packages/nibijs/docs/classes/NibiruSigningClient.md
  packages/nibijs/docs/classes/PerpMsgFactory.md
  packages/nibijs/docs/classes/SpotMsgFactory.md
  packages/nibijs/docs/enums/BECH32_PREFIX.md
  packages/nibijs/docs/enums/Signer.md
  packages/nibijs/docs/interfaces/Attribute.md
  packages/nibijs/docs/interfaces/Chain.md
  packages/nibijs/docs/interfaces/ChainIdParts.md
  packages/nibijs/docs/interfaces/CoinMap.md
  packages/nibijs/docs/interfaces/Event.md
  packages/nibijs/docs/interfaces/MsgAddMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgClosePositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgCreatePoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgDonateToEcosystemFundEncodeObject.md
  packages/nibijs/docs/interfaces/MsgExitPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgJoinPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgMultiLiquidateEncodeObject.md
  packages/nibijs/docs/interfaces/MsgOpenPositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgRemoveMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgSwapAssetsEncodeObject.md
  packages/nibijs/docs/interfaces/MsgTypeUrls.md
  packages/nibijs/docs/interfaces/TxLog.md
  packages/nibijs/docs/interfaces/TxMessage.md
  packages/nibijs/docs/intro.md
  packages/nibijs/docs/modules.md
  packages/nibijs/package.json
  packages/nibijs/src/wallet/keplr.ts
  packages/protojs/package.json
  yarn.lock
Labels: type: feat

#171 feat(protojs): add gRPC clients via connect-es
  packages/protojs/src/nibiru/epochs/v1/query_connect.ts
  packages/protojs/src/nibiru/inflation/v1/query_connect.ts
  packages/protojs/src/nibiru/oracle/v1/query_connect.ts
  packages/protojs/src/nibiru/oracle/v1/tx_connect.ts
  packages/protojs/src/nibiru/perp/v2/query_connect.ts
  packages/protojs/src/nibiru/perp/v2/tx_connect.ts
  packages/protojs/src/nibiru/spot/v1/query_connect.ts
  packages/protojs/src/nibiru/spot/v1/tx_connect.ts
  packages/protojs/src/nibiru/stablecoin/v1/query_connect.ts
  packages/protojs/src/nibiru/stablecoin/v1/tx_connect.ts
  packages/protojs/src/nibiru/sudo/v1/query_connect.ts
  packages/protojs/src/nibiru/sudo/v1/tx_connect.ts
Labels: type: feat
