Repository NibiruChain/ts-sdk, pull requests merged in 2023-12, with the labels that each got.

#257 fix(nibijs): NibiruQueryClient must expose methods from the Tendermint client
  packages/nibijs/docs/classes/CustomChain.md
  packages/nibijs/docs/classes/MsgFactory.md
  packages/nibijs/docs/classes/NibiruQueryClient.md
  packages/nibijs/docs/classes/NibiruSigningClient.md
  packages/nibijs/docs/classes/PerpMsgFactory.md
  packages/nibijs/docs/classes/SpotMsgFactory.md
  packages/nibijs/docs/classes/StableSwap.md
  packages/nibijs/docs/enums/BECH32_PREFIX.md
  packages/nibijs/docs/enums/Signer.md
  packages/nibijs/docs/interfaces/ABCIEvent.md
  packages/nibijs/docs/interfaces/Chain.md
  packages/nibijs/docs/interfaces/ChainIdParts.md
  packages/nibijs/docs/interfaces/EpochsExtension.md
  packages/nibijs/docs/interfaces/EventAttribute.md
  packages/nibijs/docs/interfaces/EventMap.md
  packages/nibijs/docs/interfaces/InflationExtension.md
  packages/nibijs/docs/interfaces/MsgAddMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgClosePositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgCreatePoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgDonateToEcosystemFundEncodeObject.md
  packages/nibijs/docs/interfaces/MsgExitPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgJoinPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgMultiLiquidateEncodeObject.md
  packages/nibijs/docs/interfaces/MsgOpenPositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgPartialCloseEncodeObject.md
  packages/nibijs/docs/interfaces/MsgRemoveMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgSwapAssetsEncodeObject.md
  packages/nibijs/docs/interfaces/OracleExtension.md
  packages/nibijs/docs/interfaces/PageRequest.md
  packages/nibijs/docs/interfaces/PerpExtension.md
  packages/nibijs/docs/interfaces/SpotExtension.md
  packages/nibijs/docs/interfaces/SudoExtension.md
  packages/nibijs/docs/interfaces/TxLog.md
  packages/nibijs/docs/modules.md
  packages/nibijs/src/query/query.ts
Labels: type: bug/fix

#262 refactor: custom chain for mainnet
  package.json
  packages/nibijs/docs/classes/StableSwap.md
  packages/nibijs/src/chain/chain.ts
  packages/nibijs/src/test/chain.test.ts
Labels: type: refactor

#269 refactor: adding hm & ws to custom chain
  packages/nibijs/docs/classes/CustomChain.md
  packages/nibijs/docs/classes/MsgFactory.md
  packages/nibijs/docs/classes/NibiruQuerier.md
  packages/nibijs/docs/classes/NibiruTxClient.md
  packages/nibijs/docs/classes/PerpMsgFactory.md
  packages/nibijs/docs/classes/Result.md
  packages/nibijs/docs/classes/SpotMsgFactory.md
  packages/nibijs/docs/classes/StableSwap.md
  packages/nibijs/docs/enums/BECH32_PREFIX.md
  packages/nibijs/docs/enums/Signer.md
  packages/nibijs/docs/interfaces/ABCIEvent.md
  packages/nibijs/docs/interfaces/Chain.md
  packages/nibijs/docs/interfaces/ChainIdParts.md
  packages/nibijs/docs/interfaces/EpochsExtension.md
  packages/nibijs/docs/interfaces/EventAttribute.md
  packages/nibijs/docs/interfaces/InflationExtension.md
  packages/nibijs/docs/interfaces/MsgAddMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgClosePositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgCreatePoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgDonateToEcosystemFundEncodeObject.md
  packages/nibijs/docs/interfaces/MsgExitPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgJoinPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgMultiLiquidateEncodeObject.md
  packages/nibijs/docs/interfaces/MsgOpenPositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgPartialCloseEncodeObject.md
  packages/nibijs/docs/interfaces/MsgRemoveMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgSwapAssetsEncodeObject.md
  packages/nibijs/docs/interfaces/OracleExtension.md
  packages/nibijs/docs/interfaces/PageRequest.md
  packages/nibijs/docs/interfaces/PerpExtension.md
  packages/nibijs/docs/interfaces/SpotExtension.md
  packages/nibijs/docs/interfaces/SudoExtension.md
  packages/nibijs/docs/modules.md
  packages/nibijs/src/chain/chain.ts
  packages/nibijs/src/test/chain.test.ts
Labels: type: enhance

#268 feat(nibijs): mainnet custom chain function
  packages/examples/package.json
  packages/nibijs/docs/classes/CustomChain.md
  packages/nibijs/docs/classes/MsgFactory.md
  packages/nibijs/docs/classes/NibiruQuerier.md
  packages/nibijs/docs/classes/NibiruTxClient.md
  packages/nibijs/docs/classes/PerpMsgFactory.md
  packages/nibijs/docs/classes/Result.md
  packages/nibijs/docs/classes/SpotMsgFactory.md
  packages/nibijs/docs/classes/StableSwap.md
  packages/nibijs/docs/enums/BECH32_PREFIX.md
  packages/nibijs/docs/enums/Signer.md
  packages/nibijs/docs/interfaces/ABCIEvent.md
  packages/nibijs/docs/interfaces/Chain.md
  packages/nibijs/docs/interfaces/ChainIdParts.md
  packages/nibijs/docs/interfaces/EpochsExtension.md
  packages/nibijs/docs/interfaces/EventAttribute.md
  packages/nibijs/docs/interfaces/EventMap.md
  packages/nibijs/docs/interfaces/InflationExtension.md
  packages/nibijs/docs/interfaces/MsgAddMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgClosePositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgCreatePoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgDonateToEcosystemFundEncodeObject.md
  packages/nibijs/docs/interfaces/MsgExitPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgJoinPoolEncodeObject.md
  packages/nibijs/docs/interfaces/MsgMultiLiquidateEncodeObject.md
  packages/nibijs/docs/interfaces/MsgOpenPositionEncodeObject.md
  packages/nibijs/docs/interfaces/MsgPartialCloseEncodeObject.md
  packages/nibijs/docs/interfaces/MsgRemoveMarginEncodeObject.md
  packages/nibijs/docs/interfaces/MsgSwapAssetsEncodeObject.md
  packages/nibijs/docs/interfaces/OracleExtension.md
  packages/nibijs/docs/interfaces/PageRequest.md
  packages/nibijs/docs/interfaces/PerpExtension.md
  packages/nibijs/docs/interfaces/SpotExtension.md
  packages/nibijs/docs/interfaces/SudoExtension.md
  packages/nibijs/docs/interfaces/TxLog.md
  packages/nibijs/docs/modules.md
  packages/nibijs/src/chain/chain.ts
  packages/nibijs/src/test/chain.test.ts
  packages/nibijs/src/test/faucet.test.ts
Labels: type: enhance
