Repository NibiruChain/ts-sdk, pull requests merged in 2023-05, with the labels that each got.

#140 Add Auth extension
  packages/nibijs/src/query/query.ts
  packages/nibijs/src/test/query.test.ts
  packages/nibijs/src/tx/signingClient.ts
Labels: type: feat

#142 Use lts/gallium with fresh install, and upgrade cosmjs-types
  .github/workflows/test-indexer-nibi.yaml
  .github/workflows/test-nibijs.yaml
  .nvmrc
  packages/nibijs/docs/classes/CustomChain.md
  packages/nibijs/docs/classes/NibiruQueryClient.md
  packages/nibijs/docs/classes/NibiruSigningClient.md
  packages/nibijs/docs/enums/BECH32_PREFIX.md
  packages/nibijs/docs/enums/Signer.md
  packages/nibijs/docs/interfaces/Attribute.md
  packages/nibijs/docs/interfaces/Chain.md
  packages/nibijs/docs/interfaces/ChainIdParts.md
  packages/nibijs/docs/interfaces/Event.md
  packages/nibijs/docs/interfaces/TxLog.md
  packages/nibijs/docs/modules.md
  packages/nibijs/package.json
  yarn.lock
Labels: type: refactor, dependencies

#153 fix: release version
  .github/workflows/test-indexer-nibi.yaml
  packages/nibijs/docs/classes/CustomChain.md
  packages/nibijs/docs/classes/NibiruQueryClient.md
  packages/nibijs/docs/classes/NibiruSigningClient.md
  packages/nibijs/docs/enums/BECH32_PREFIX.md
  packages/nibijs/docs/enums/Signer.md
  packages/nibijs/docs/interfaces/Attribute.md
  packages/nibijs/docs/interfaces/Chain.md
  packages/nibijs/docs/interfaces/ChainIdParts.md
  packages/nibijs/docs/interfaces/CoinMap.md
  packages/nibijs/docs/interfaces/Event.md
  packages/nibijs/docs/interfaces/TxLog.md
  packages/nibijs/docs/intro.md
  packages/nibijs/docs/modules.md
  packages/nibijs/package.json
Labels: type: bug/fix
